# Generated by Django 2.2.10 on 2020-02-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
    ]
