# Generated by Django 2.2.10 on 2020-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_auto_20200224_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='premiere',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='price',
        ),
        migrations.AddField(
            model_name='producto',
            name='pathname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
