# Generated by Django 2.2.10 on 2020-02-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20200224_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='premiere',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pathname',
        ),
    ]
