# Generated by Django 2.2.10 on 2020-02-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_auto_20200224_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgpath',
            field=models.CharField(default='', max_length=50),
        ),
    ]
