# Generated by Django 2.2.10 on 2020-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0007_auto_20200224_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='firsteq',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='secondeq',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='thirdeq',
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.FloatField(),
        ),
    ]
