# Generated by Django 2.2.10 on 2020-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0008_auto_20200224_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imgpath',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
