# Generated by Django 2.2.10 on 2020-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0009_producto_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prodpath',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
