# Generated by Django 2.2.10 on 2020-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0012_auto_20200302_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prodid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
