# Generated by Django 2.2.10 on 2020-03-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0013_producto_prodid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='prodid',
        ),
    ]
