# Generated by Django 2.2.10 on 2020-03-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0014_remove_producto_prodid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='producto',
            new_name='product',
        ),
    ]
