# Generated by Django 2.2.10 on 2020-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0016_auto_20200302_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cart',
            field=models.CharField(default='{}', max_length=250),
        ),
    ]
