# Generated by Django 2.2.10 on 2020-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0017_auto_20200303_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cart',
            field=models.CharField(default='[]', max_length=250),
        ),
    ]
