# Generated by Django 2.2.10 on 2020-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0019_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
